### ISSUE TITLE
How TCP Sockets Work

### ISSUE THREAD

**Issue by brantou** [brantou/reading#695]
<b>How TCP Sockets Work</b><br>
In this post I&rsquo;m going to explain at a high level how the TCP/IP stack works onLinux. In particular, I&rsquo;ll explore how the socket system calls interact&hellip;<br>
<br>
August 9, 2019 at 12:07PM<br>
via Instapaper https://eklitzke.org/how-tcp-sockets-work

**Comment by hustshawn** [comment]
Hi @brantou , 
纯好奇问下，你这个repo里关于reading的每一个issue是你手动建立的，还是你automate的结果（比如读到的文章mark在pocket/readlater这样的平台，然后trigger 建立一个git issue）?
